_wandb:
    value:
        cli_version: 0.23.1
        e:
            kvmo9irz0bbfqkjc284livg676pfoqm6:
                codePath: src/my_project/train_d4.py
                codePathLocal: src/my_project/train_d4.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "269427478528"
                        used: "14965039104"
                email: viktor.skovgaard@gmail.com
                executable: /home/s211222/MLOps/.venv/bin/python3
                host: LenovoPrime
                memory:
                    total: "7188197376"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.31
                program: /home/s211222/MLOps/src/my_project/train_d4.py
                python: CPython 3.11.7
                root: /home/s211222/MLOps
                startedAt: "2026-01-08T13:29:18.250639Z"
                writerId: kvmo9irz0bbfqkjc284livg676pfoqm6
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.11.7
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
